name: githubaction3
on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main
 workflow_dispatch:
 schedule: 
  - cron: "0 0 * * *"

jobs:
 jobs1:
  runs-on: ubuntu-latest
  steps:
  - name: printhello
    run: echo "hello world"
 jobs2:
  runs-on: ubuntu-latest
  steps:
  - name: envandsecrets
    env: 
     name: "chiku"
     password: ${{secrets.PASSWORD}}
    run: echo " name is $name and password is $password"
 jobs3:
  runs-on: ubuntu-latest
  steps:
  - name: uploadartifact
    run: echo "chiku is" > first.txt
  - name: uploadit 
    uses: actions/upload-artifact@v4
    with:
     name: uploadartifacts
     path: first.txt
 jobs4:
  runs-on: ubuntu-latest
  steps:
  - name: downloadit
    uses: actions/download-artifact@v4
    with:
     name: uploadaritfacts
  - name: run cat 
    run: cat first.txt
  
  
  

  
